import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Cocktail from "@/components/cocktail";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Kickback at Kwamina&apos;s</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1 maximum-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.headerAnimation}>Kickback at Kwamina&apos;s</h1>

        <div className={styles.cocktailContainer}>
          <Cocktail
            name={"House Margarita"}
            ingredients={["tequila", "triple sec", "orange juice"]}
          />
          <Cocktail
            name={"The RFP"}
            ingredients={[
              "rum",
              "fresh mint",
              "lime juice",
              "simple syrup",
              "club soda",
            ]}
          />
          <Cocktail
            name={"The Olive You, Baby"}
            ingredients={["vodka", "dry vermouth", "orange bitters", "olives"]}
          />
          <Cocktail
            name={"Daiq-yeah-ri"}
            ingredients={["rum", "simple syrup", "lime juice"]}
          />
          <Cocktail
            name={"Might Call Out Tomorrow"}
            ingredients={["tequila", "rum", "triple sec", "cranberry juice"]}
          />
          <Cocktail
            name={"Go off"}
            ingredients={["whatever combinations of liquor I make, juice"]}
          />
        </div>
      </main>
    </>
  );
}
